name: Deploy Go Project to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22.4'

    - name: Build the Go project
      run: |
        mkdir -p build
        go build -o build/myapp ./

    - name: Archive the build artifacts
      run: zip -r build.zip build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: build
        path: build.zip

    - name: Print current directory
      run: |
        pwd
        ls -l

    - name: List artifacts
      run: |
        ls -l
        unzip -l build.zip

    - name: Extract build artifacts
      run: |
        unzip build.zip -d build || echo "Failed to unzip build.zip: $?"

    - name: List extracted files
      run: |
        ls -l build

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo systemctl stop myapp
          rm -rf /home/ec2-user/myapp
          mkdir -p /home/ec2-user/myapp
          mv build/myapp /home/ec2-user/myapp/
          sudo systemctl start myapp
